http:
  port: 8000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

auth:
  accessTokenTTL: 720h
  refreshTokenTTL: 720h #30 days
  verificationCodeLength: 8

postgres:
  databaseName: shotwot_test